### ISSUE TITLE
Could you do this natively?

### ISSUE THREAD

**Issue by oijdfdg** [two-six/scss_mass_compiler#1]
[My application](https://github.com/j4cegh/cwf) currently plans on not depending on external applications such as `node`. Could you do the same exact thing, just without any external applications? Thanks!

**Comment by xcdkz** [comment]
Hey, it now works natively so feel free to use it.

**Comment by oijdfdg** [comment]
> Hey, it now works natively so feel free to use it.

Thank you so much!! I'll for sure consider using it when adding scss support. :)
